name: tweet from json
#reads json file and parses them into tweets to be sent to twitter

on: 
#	schedule:
#        - cron:  '00 17 * * *' # triggers workflow every day at 10 am
    workflow_dispatch: # allows for manual trigger
        
jobs:
    run_python_script_to_tweet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                ref: main
            - name: set up docker, alpine and python
              run: |
                sudo apt-get remove docker docker-engine docker.io
                sudo apt-get update
                sudo apt install docker.io
                sudo snap install docker
                sudo docker run -it alpine:3
                apk add python3
